name: Acceptance Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout provider repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout TaskManager backend repo
        uses: actions/checkout@v4
        with:
          repository: shivraj1192/TaskManager-Go
          path: backend

      - name: Download Go modules for backend
        working-directory: backend
        run: go mod download

      - name: Start TaskManager backend
        working-directory: backend
        run: |
          nohup go run ./cmd/main.go > server.log 2>&1 &
          sleep 5

      - name: Run Acceptance Tests
        env:
          TF_ACC: 1
          BASE_URL: http://localhost:8080/
          TOKEN: ${{ secrets.TOKEN }}
        run: go test -v ./test_taskmanager

      - name: Show backend logs
        if: always()
        run: cat backend/server.log
