name: Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: shivraj
          POSTGRES_PASSWORD: shivraj123
          POSTGRES_DB: taskmanager
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout provider repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Checkout TaskManager backend repo
        uses: actions/checkout@v4
        with:
          repository: shivraj1192/TaskManager-Go
          path: backend

      - name: Download Go modules for backend
        working-directory: backend
        run: go mod download

      - name: Create .env file
        working-directory: backend
        run: |
          echo DB_HOST=localhost >> .env
          echo DB_PORT=5432 >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME=taskmanager >> .env

      - name: Start TaskManager backend
        working-directory: backend
        run: |
          nohup go run ./cmd/main.go > server.log 2>&1 &
          sleep 5

      - name: Run Acceptance Tests
        env:
          TF_ACC: 1
          BASE_URL: http://localhost:8080/
          TOKEN: ${{ secrets.TOKEN }}
        run: go test -v ./test_taskmanager

      - name: Show backend logs
        if: always()
        run: cat backend/server.log
